/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code. Do not edit.

using System.Text.Json.Serialization;
using System.Collections.Generic;
using System.Text.Json;

namespace Google.GenAI.Types {
  /// <summary>
  /// The reason why the turn is complete.
  /// </summary>

  [JsonConverter(typeof(TurnCompleteReasonConverter))]
  public readonly record struct TurnCompleteReason : IEquatable<TurnCompleteReason> {
    public string Value { get; }

    private TurnCompleteReason(string value) {
      Value = value;
    }

    /// <summary>
    /// Default value. Reason is unspecified.
    /// </summary>
    public static TurnCompleteReason TurnCompleteReasonUnspecified {
      get;
    } = new("TURN_COMPLETE_REASON_UNSPECIFIED");

    /// <summary>
    /// The function call generated by the model is invalid.
    /// </summary>
    public static TurnCompleteReason MalformedFunctionCall {
      get;
    } = new("MALFORMED_FUNCTION_CALL");

    /// <summary>
    /// The response is rejected by the model.
    /// </summary>
    public static TurnCompleteReason ResponseRejected { get; } = new("RESPONSE_REJECTED");

    /// <summary>
    /// Needs more input from the user.
    /// </summary>
    public static TurnCompleteReason NeedMoreInput { get; } = new("NEED_MORE_INPUT");

    public static IReadOnlyList<TurnCompleteReason> AllValues {
      get;
    } = new[] { TurnCompleteReasonUnspecified, MalformedFunctionCall, ResponseRejected,
                NeedMoreInput };

    public static TurnCompleteReason FromString(string value) {
      if (string.IsNullOrEmpty(value)) {
        return new TurnCompleteReason("TURN_COMPLETE_REASON_UNSPECIFIED");
      }

      foreach (var known in AllValues) {
        if (known.Value == value) {
          return known;
        }
      }

      return new TurnCompleteReason(value);
    }

    public override string ToString() => Value ?? string.Empty;

    public static implicit operator TurnCompleteReason(string value) => FromString(value);

    public bool Equals(TurnCompleteReason other) => Value == other.Value;

    public override int GetHashCode() => Value?.GetHashCode() ?? 0;
  }

  public class TurnCompleteReasonConverter : JsonConverter<TurnCompleteReason> {
    public override TurnCompleteReason Read(ref Utf8JsonReader reader, System.Type typeToConvert,
                                            JsonSerializerOptions options) {
      var value = reader.GetString();
      return TurnCompleteReason.FromString(value);
    }

    public override void Write(Utf8JsonWriter writer, TurnCompleteReason value,
                               JsonSerializerOptions options) {
      writer.WriteStringValue(value.Value);
    }
  }
}
